import { useState } from 'react'
import { Link, NavLink, Outlet } from 'react-router'
import { BookOpenCheck, Menu, Sun, Moon, Monitor, ChevronDown, LogOut, Settings, UserRound, MessageSquare, History, Library, Database, Search, Users } from 'lucide-react'
import { useAuth } from '@/auth/store'
import { useTheme, type Theme } from '@/lib/theme'
import { Button } from './ui/button'
import { Badge } from './ui/badge'
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuRadioGroup, DropdownMenuRadioItem } from './ui/dropdown-menu'
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from './ui/sheet'
const links = [{ to: '/', label: '提问', icon: MessageSquare }, { to: '/history', label: '历史', icon: History }, { to: '/library', label: '文献库', icon: Library }, { to: '/kb', label: '知识库', icon: Database }, { to: '/search', label: '查文献', icon: Search }, { to: '/admin/users', label: '用户', icon: Users }]
export function AppShell() {
  const { user, isAdmin, logout } = useAuth()
  const { theme, setTheme, resolved } = useTheme()
  const [menuOpen, setMenuOpen] = useState(false)
  const navigation = (mobile = false) => links.filter(link => isAdmin || link.to !== '/admin/users').map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} end={to === '/'} onClick={() => setMenuOpen(false)} className={({ isActive }) => (mobile ? 'mobile-nav ' : 'top-nav ') + (isActive ? 'active' : '')}><Icon className="size-4" />{label}</NavLink>)
  return <><header className="app-header"><div className="flex min-w-0 items-center gap-3"><Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetTrigger asChild><Button className="md:hidden" variant="ghost" size="icon" aria-label="打开导航"><Menu /></Button></SheetTrigger><SheetContent side="left"><SheetHeader><SheetTitle>YAOpenEvidence</SheetTitle></SheetHeader><nav className="grid gap-1 px-3">{navigation(true)}</nav></SheetContent></Sheet><Link to="/" className="brand"><BookOpenCheck className="size-7 shrink-0 text-primary" strokeWidth={1.7} /><span>YAOpen<span className="text-primary">Evidence</span></span></Link></div><nav aria-label="主导航" className="hidden h-full items-center gap-1 md:flex">{navigation()}</nav><div className="flex shrink-0 items-center gap-1"><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label="切换主题" title="切换主题">{resolved === 'dark' ? <Moon /> : <Sun />}</Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuRadioGroup value={theme} onValueChange={v => setTheme(v as Theme)}>{([{value:'system',label:'跟随系统',icon:Monitor},{value:'light',label:'浅色',icon:Sun},{value:'dark',label:'深色',icon:Moon}]).map(({value,label,icon:Icon}) => <DropdownMenuRadioItem key={value} value={value}><Icon />{label}</DropdownMenuRadioItem>)}</DropdownMenuRadioGroup></DropdownMenuContent></DropdownMenu><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" className="max-w-44" aria-label="用户菜单"><span className="avatar"><UserRound className="size-4" /></span><span className="hidden truncate lg:inline">{user?.username}</span><ChevronDown className="size-3" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-52"><div className="flex items-center justify-between gap-2 px-2 py-3 text-sm"><span className="truncate">{user?.username}</span><Badge variant="secondary">{isAdmin ? '管理员' : '用户'}</Badge></div><DropdownMenuSeparator /><DropdownMenuItem asChild><Link to="/account"><Settings />账号设置</Link></DropdownMenuItem><DropdownMenuItem onClick={() => void logout()}><LogOut />退出登录</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header><main id="main-content"><Outlet /></main></>
}
